"""The world in the autumn of 1402, after the Battle of Ankara: provinces and who holds them.

The source of truth for the map's provinces (tools/provinces.py turns it into crowns/data/map/).
Each province: id, name, longitude, latitude (of its main town), owner, culture, religion.
Owners as of September 1402: Bayezid I is Timur's prisoner and his sons divide the Ottoman lands
(Süleyman in Rumelia, İsa at Bursa, Mehmed at Amasya); Timur has given the Anatolian beyliks back
to their old dynasties. Later changes (Thessaloniki back to Byzantium in 1403, Belgrade to Serbia in
1403/04, Dobruja to Wallachia in 1404, ...) are left to the campaign's events.
"""

# id, name, lon, lat, owner, culture, religion
PROVINCES = [
    # --- Kingdom of Hungary -------------------------------------------------------------------------
    ("buda", "Buda", 19.04, 47.50, "hungary", "hungarian", "catholic"),
    ("esztergom", "Esztergom", 18.74, 47.79, "hungary", "hungarian", "catholic"),
    ("gyor", "Győr", 17.63, 47.69, "hungary", "hungarian", "catholic"),
    ("pozsony", "Pozsony", 17.11, 48.15, "hungary", "slovak", "catholic"),
    ("nyitra", "Nyitra", 18.08, 48.31, "hungary", "slovak", "catholic"),
    ("trencsen", "Trencsén", 18.04, 48.89, "hungary", "slovak", "catholic"),
    ("zolyom", "Zólyom", 19.15, 48.73, "hungary", "slovak", "catholic"),
    ("szepes", "Szepes", 20.56, 49.00, "hungary", "slovak", "catholic"),
    ("kassa", "Kassa", 21.26, 48.72, "hungary", "hungarian", "catholic"),
    ("eger", "Eger", 20.38, 47.90, "hungary", "hungarian", "catholic"),
    ("debrecen", "Debrecen", 21.63, 47.53, "hungary", "hungarian", "catholic"),
    ("szatmar", "Szatmár", 22.88, 47.79, "hungary", "hungarian", "catholic"),
    ("varad", "Várad", 21.92, 47.06, "hungary", "hungarian", "catholic"),
    ("szolnok", "Szolnok", 20.20, 47.17, "hungary", "hungarian", "catholic"),
    ("szeged", "Szeged", 20.15, 46.25, "hungary", "hungarian", "catholic"),
    ("kalocsa", "Kalocsa", 18.98, 46.53, "hungary", "hungarian", "catholic"),
    ("pecs", "Pécs", 18.23, 46.07, "hungary", "hungarian", "catholic"),
    ("fehervar", "Székesfehérvár", 18.41, 47.19, "hungary", "hungarian", "catholic"),
    ("veszprem", "Veszprém", 17.91, 47.09, "hungary", "hungarian", "catholic"),
    ("sopron", "Sopron", 16.59, 47.68, "hungary", "german", "catholic"),
    ("vas", "Vas", 16.62, 47.23, "hungary", "hungarian", "catholic"),
    ("zala", "Zala", 16.85, 46.84, "hungary", "hungarian", "catholic"),
    ("somogy", "Somogy", 17.80, 46.40, "hungary", "hungarian", "catholic"),
    ("temes", "Temesvár", 21.23, 45.75, "hungary", "hungarian", "catholic"),
    ("arad", "Arad", 21.31, 46.18, "hungary", "hungarian", "catholic"),
    ("bacs", "Bács", 19.35, 45.95, "hungary", "hungarian", "catholic"),
    ("szerem", "Szerém", 19.60, 45.05, "hungary", "serbian", "orthodox"),
    ("belgrade", "Belgrade", 20.46, 44.82, "hungary", "serbian", "orthodox"),
    ("severin", "Severin", 22.66, 44.63, "hungary", "romanian", "orthodox"),
    ("karansebes", "Karánsebes", 22.22, 45.42, "hungary", "romanian", "orthodox"),
    ("zagreb", "Zagreb", 15.98, 45.81, "hungary", "croatian", "catholic"),
    ("varasd", "Varasd", 16.34, 46.30, "hungary", "croatian", "catholic"),
    ("pozsega", "Pozsega", 17.68, 45.33, "hungary", "croatian", "catholic"),
    ("valko", "Valkó", 18.80, 45.40, "hungary", "croatian", "catholic"),
    ("lika", "Lika", 15.30, 44.60, "hungary", "croatian", "catholic"),
    ("knin", "Knin", 16.20, 44.04, "hungary", "croatian", "catholic"),
    ("zara", "Zara", 15.23, 44.12, "hungary", "croatian", "catholic"),
    ("spalato", "Spalato", 16.44, 43.51, "hungary", "croatian", "catholic"),
    ("bihac", "Bihać", 15.87, 44.81, "hungary", "croatian", "catholic"),
    ("kotor", "Cattaro", 18.77, 42.42, "hungary", "serbian", "catholic"),
    ("modrus", "Modruš", 15.00, 45.15, "frankopan", "croatian", "catholic"),
    # Transylvania
    ("kolozsvar", "Kolozsvár", 23.60, 46.77, "hungary", "hungarian", "catholic"),
    ("gyulafehervar", "Gyulafehérvár", 23.58, 46.07, "hungary", "hungarian", "catholic"),
    ("hunyad", "Hunyad", 22.90, 45.75, "hungary", "romanian", "orthodox"),
    ("szeben", "Szeben", 24.15, 45.79, "hungary", "german", "catholic"),
    ("brasso", "Brassó", 25.59, 45.65, "hungary", "german", "catholic"),
    ("beszterce", "Beszterce", 24.50, 47.13, "hungary", "german", "catholic"),
    ("szekelyfold", "Székely Land", 25.60, 46.30, "hungary", "hungarian", "catholic"),
    ("maros", "Maros", 24.56, 46.54, "hungary", "hungarian", "catholic"),
    ("maramaros", "Máramaros", 24.00, 47.85, "hungary", "romanian", "orthodox"),
    ("fagaras", "Făgăraș", 24.97, 45.84, "wallachia", "romanian", "orthodox"),

    # --- Austria, Bohemia and the western edge ---------------------------------------------------------
    ("vienna", "Vienna", 16.37, 48.21, "austria", "german", "catholic"),
    ("linz", "Upper Austria", 14.29, 48.31, "austria", "german", "catholic"),
    ("graz", "Styria", 15.44, 47.07, "austria", "german", "catholic"),
    ("carinthia", "Carinthia", 14.30, 46.62, "austria", "german", "catholic"),
    ("carniola", "Carniola", 14.50, 46.05, "austria", "slovene", "catholic"),
    ("trieste", "Trieste", 13.77, 45.65, "austria", "italian", "catholic"),
    ("celje", "Celje", 15.26, 46.23, "celje", "slovene", "catholic"),
    ("friuli", "Friuli", 13.23, 46.06, "aquileia", "italian", "catholic"),
    ("istria", "Istria", 13.85, 45.15, "venice", "italian", "catholic"),
    ("salzburg", "Salzburg", 13.04, 47.80, "salzburg", "german", "catholic"),
    ("landshut", "Lower Bavaria", 12.90, 48.60, "bavaria", "german", "catholic"),
    ("prague", "Prague", 14.42, 50.08, "bohemia", "czech", "catholic"),
    ("plzen", "Plzeň", 13.38, 49.75, "bohemia", "czech", "catholic"),
    ("budweis", "Budweis", 14.47, 48.97, "bohemia", "czech", "catholic"),
    ("hradec", "Hradec", 15.83, 50.21, "bohemia", "czech", "catholic"),
    ("breslau", "Breslau", 17.03, 51.11, "bohemia", "german", "catholic"),
    ("opava", "Opava", 17.90, 49.94, "bohemia", "czech", "catholic"),
    ("brno", "Brno", 16.61, 49.20, "moravia", "czech", "catholic"),
    ("olomouc", "Olomouc", 17.25, 49.59, "moravia", "czech", "catholic"),

    # --- Poland and Lithuania ----------------------------------------------------------------------------
    ("krakow", "Kraków", 19.94, 50.06, "poland", "polish", "catholic"),
    ("sandomierz", "Sandomierz", 21.75, 50.68, "poland", "polish", "catholic"),
    ("lublin", "Lublin", 22.57, 51.25, "poland", "polish", "catholic"),
    ("chelm", "Chełm", 23.47, 51.13, "poland", "ruthenian", "orthodox"),
    ("lwow", "Lwów", 24.03, 49.84, "poland", "ruthenian", "orthodox"),
    ("przemysl", "Przemyśl", 22.77, 49.78, "poland", "ruthenian", "orthodox"),
    ("halicz", "Halicz", 24.72, 49.12, "poland", "ruthenian", "orthodox"),
    ("belz", "Bełz", 24.00, 50.38, "poland", "ruthenian", "orthodox"),
    ("kamieniec", "Kamieniec", 26.58, 48.68, "poland", "ruthenian", "orthodox"),
    ("lutsk", "Lutsk", 25.33, 50.75, "lithuania", "ruthenian", "orthodox"),
    ("volodymyr", "Volodymyr", 24.33, 50.85, "lithuania", "ruthenian", "orthodox"),
    ("kremenets", "Kremenets", 25.72, 50.10, "lithuania", "ruthenian", "orthodox"),
    ("kyiv", "Kyiv", 30.52, 50.45, "lithuania", "ruthenian", "orthodox"),
    ("zhytomyr", "Zhytomyr", 28.66, 50.25, "lithuania", "ruthenian", "orthodox"),
    ("bratslav", "Bratslav", 28.47, 49.23, "lithuania", "ruthenian", "orthodox"),
    ("chernihiv", "Chernihiv", 31.29, 51.49, "lithuania", "ruthenian", "orthodox"),
    ("pereiaslav", "Pereiaslav", 31.45, 50.06, "lithuania", "ruthenian", "orthodox"),
    ("cherkasy", "Cherkasy", 32.06, 49.44, "lithuania", "ruthenian", "orthodox"),
    ("khadjibey", "Khadjibey", 30.73, 46.48, "lithuania", "tatar", "sunni"),

    # --- Moldavia and Wallachia ----------------------------------------------------------------------------
    ("suceava", "Suceava", 26.25, 47.65, "moldavia", "romanian", "orthodox"),
    ("hotin", "Hotin", 26.50, 48.48, "moldavia", "romanian", "orthodox"),
    ("soroca", "Soroca", 28.30, 48.16, "moldavia", "romanian", "orthodox"),
    ("iasi", "Iași", 27.59, 47.16, "moldavia", "romanian", "orthodox"),
    ("roman", "Roman", 26.92, 46.95, "moldavia", "romanian", "orthodox"),
    ("orhei", "Orhei", 28.82, 47.38, "moldavia", "romanian", "orthodox"),
    ("lapusna", "Lăpușna", 28.40, 46.88, "moldavia", "romanian", "orthodox"),
    ("barlad", "Bârlad", 27.67, 46.23, "moldavia", "romanian", "orthodox"),
    ("putna", "Putna", 27.18, 45.70, "moldavia", "romanian", "orthodox"),
    ("cetatea_alba", "Cetatea Albă", 30.35, 46.19, "moldavia", "romanian", "orthodox"),
    ("chilia", "Chilia", 29.25, 45.43, "genoa", "romanian", "orthodox"),
    ("arges", "Argeș", 24.68, 45.15, "wallachia", "romanian", "orthodox"),
    ("targoviste", "Târgoviște", 25.45, 44.93, "wallachia", "romanian", "orthodox"),
    ("craiova", "Craiova", 23.80, 44.32, "wallachia", "romanian", "orthodox"),
    ("gorj", "Jiu", 23.27, 45.04, "wallachia", "romanian", "orthodox"),
    ("caracal", "Romanați", 24.35, 44.11, "wallachia", "romanian", "orthodox"),
    ("teleorman", "Teleorman", 25.30, 44.15, "wallachia", "romanian", "orthodox"),
    ("giurgiu", "Giurgiu", 25.97, 43.95, "wallachia", "romanian", "orthodox"),
    ("vlasia", "Vlăsia", 26.10, 44.50, "wallachia", "romanian", "orthodox"),
    ("buzau", "Buzău", 26.82, 45.15, "wallachia", "romanian", "orthodox"),
    ("braila", "Brăila", 27.96, 45.27, "wallachia", "romanian", "orthodox"),
    ("ialomita", "Ialomița", 27.40, 44.60, "wallachia", "romanian", "orthodox"),

    # --- Ottoman Rumelia (Süleyman Çelebi): Bulgaria, Thrace, Macedonia, Thessaly ------------------------------
    ("vidin", "Vidin", 22.88, 43.99, "ott_rum", "bulgarian", "orthodox"),
    ("nikopol", "Nikopol", 24.90, 43.70, "ott_rum", "bulgarian", "orthodox"),
    ("tarnovo", "Tarnovo", 25.63, 43.08, "ott_rum", "bulgarian", "orthodox"),
    ("lovech", "Lovech", 24.72, 43.13, "ott_rum", "bulgarian", "orthodox"),
    ("sofia", "Sofia", 23.32, 42.70, "ott_rum", "bulgarian", "orthodox"),
    ("vratsa", "Vratsa", 23.55, 43.20, "ott_rum", "bulgarian", "orthodox"),
    ("silistra", "Silistra", 27.26, 44.12, "ott_rum", "bulgarian", "orthodox"),
    ("ruse", "Ruse", 26.00, 43.60, "ott_rum", "bulgarian", "orthodox"),
    ("shumen", "Shumen", 26.92, 43.27, "ott_rum", "bulgarian", "orthodox"),
    ("varna", "Varna", 27.91, 43.21, "ott_rum", "bulgarian", "orthodox"),
    ("dobruja", "Dobruja", 28.30, 44.40, "ott_rum", "bulgarian", "orthodox"),
    ("philippopolis", "Philippopolis", 24.75, 42.15, "ott_rum", "bulgarian", "orthodox"),
    ("zagora", "Zagora", 25.63, 42.42, "ott_rum", "bulgarian", "orthodox"),
    ("yambol", "Yambol", 26.50, 42.48, "ott_rum", "bulgarian", "orthodox"),
    ("anchialos", "Anchialos", 27.52, 42.55, "ott_rum", "greek", "orthodox"),
    ("kyustendil", "Velbazhd", 22.69, 42.28, "ott_rum", "bulgarian", "orthodox"),
    ("nis", "Niš", 21.90, 43.32, "ott_rum", "serbian", "orthodox"),
    ("edirne", "Edirne", 26.56, 41.68, "ott_rum", "turkish", "sunni"),
    ("gallipoli", "Gallipoli", 26.67, 40.41, "ott_rum", "turkish", "sunni"),
    ("rodosto", "Rodosto", 27.50, 40.98, "ott_rum", "greek", "orthodox"),
    ("kirkkilise", "Kırk Kilise", 27.23, 41.73, "ott_rum", "greek", "orthodox"),
    ("komotini", "Gümülcine", 25.40, 41.12, "ott_rum", "greek", "orthodox"),
    ("serres", "Serres", 23.55, 41.09, "ott_rum", "greek", "orthodox"),
    ("christoupolis", "Christoupolis", 24.40, 40.94, "ott_rum", "greek", "orthodox"),
    ("thessaloniki", "Thessaloniki", 22.94, 40.64, "ott_rum", "greek", "orthodox"),
    ("chalkidiki", "Chalkidiki", 23.60, 40.30, "ott_rum", "greek", "orthodox"),
    ("veria", "Veria", 22.20, 40.52, "ott_rum", "greek", "orthodox"),
    ("kastoria", "Kastoria", 21.27, 40.52, "ott_rum", "greek", "orthodox"),
    ("monastir", "Monastir", 21.33, 41.03, "ott_rum", "bulgarian", "orthodox"),
    ("ohrid", "Ohrid", 20.80, 41.12, "ott_rum", "bulgarian", "orthodox"),
    ("skopje", "Skopje", 21.43, 42.00, "ott_rum", "serbian", "orthodox"),
    ("stip", "Štip", 22.20, 41.74, "ott_rum", "bulgarian", "orthodox"),
    ("larissa", "Larissa", 22.42, 39.64, "ott_rum", "greek", "orthodox"),
    ("trikala", "Trikala", 21.77, 39.55, "ott_rum", "greek", "orthodox"),
    ("zitouni", "Zitouni", 22.43, 38.90, "ott_rum", "greek", "orthodox"),
    ("salona", "Salona", 22.38, 38.53, "ott_rum", "greek", "orthodox"),

    # --- Byzantium, Greece and the Latin lords ------------------------------------------------------------------
    ("constantinople", "Constantinople", 28.97, 41.01, "byzantium", "greek", "orthodox"),
    ("selymbria", "Selymbria", 28.25, 41.07, "byzantium", "greek", "orthodox"),
    ("lemnos", "Lemnos", 25.25, 39.90, "byzantium", "greek", "orthodox"),
    ("thasos", "Thasos", 24.70, 40.68, "byzantium", "greek", "orthodox"),
    ("mystras", "Mystras", 22.37, 37.07, "morea", "greek", "orthodox"),
    ("monemvasia", "Monemvasia", 23.05, 36.69, "morea", "greek", "orthodox"),
    ("arcadia", "Arcadia", 22.37, 37.50, "morea", "greek", "orthodox"),
    ("corinth", "Corinth", 22.93, 37.90, "knights", "greek", "orthodox"),
    ("patras", "Patras", 21.73, 38.25, "achaea", "greek", "orthodox"),
    ("glarentza", "Glarentza", 21.25, 37.88, "achaea", "greek", "orthodox"),
    ("kalamata", "Kalamata", 22.10, 37.04, "achaea", "greek", "orthodox"),
    ("modon", "Modon and Coron", 21.70, 36.85, "venice", "greek", "orthodox"),
    ("nauplia", "Argos and Nauplia", 22.80, 37.60, "venice", "greek", "orthodox"),
    ("thebes", "Thebes", 23.32, 38.32, "athens", "greek", "orthodox"),
    ("athens", "Athens", 23.73, 37.98, "athens", "greek", "orthodox"),
    ("negroponte", "Negroponte", 23.60, 38.46, "venice", "greek", "orthodox"),
    ("ioannina", "Ioannina", 20.85, 39.67, "ioannina", "greek", "orthodox"),
    ("arta", "Arta", 20.99, 39.16, "spata", "albanian", "orthodox"),
    ("aetolia", "Aetolia", 21.60, 38.60, "spata", "albanian", "orthodox"),
    ("leucas", "Leucas", 20.70, 38.80, "tocco", "greek", "orthodox"),
    ("cephalonia", "Cephalonia", 20.50, 38.20, "tocco", "greek", "orthodox"),
    ("zakynthos", "Zakynthos", 20.90, 37.78, "tocco", "greek", "orthodox"),
    ("corfu", "Corfu", 19.90, 39.60, "venice", "greek", "orthodox"),

    # --- The Aegean, Crete and Cyprus -----------------------------------------------------------------------------
    ("lesbos", "Lesbos", 26.25, 39.15, "lesbos", "greek", "orthodox"),
    ("ainos", "Ainos", 26.08, 40.73, "lesbos", "greek", "orthodox"),
    ("chios", "Chios", 26.00, 38.40, "genoa", "greek", "orthodox"),
    ("naxos", "Naxos", 25.40, 37.07, "naxos", "greek", "orthodox"),
    ("andros", "Andros", 24.90, 37.85, "naxos", "greek", "orthodox"),
    ("santorini", "Santorini", 25.43, 36.40, "naxos", "greek", "orthodox"),
    ("rhodes", "Rhodes", 28.00, 36.20, "knights", "greek", "orthodox"),
    ("kos", "Kos", 27.20, 36.85, "knights", "greek", "orthodox"),
    ("candia", "Candia", 25.13, 35.30, "venice", "greek", "orthodox"),
    ("canea", "Canea", 24.00, 35.40, "venice", "greek", "orthodox"),
    ("nicosia", "Nicosia", 33.36, 35.17, "cyprus", "greek", "orthodox"),
    ("limassol", "Limassol", 32.90, 34.75, "cyprus", "greek", "orthodox"),
    ("famagusta", "Famagusta", 33.94, 35.12, "genoa", "greek", "orthodox"),

    # --- Serbia, Bosnia, Zeta, Ragusa ------------------------------------------------------------------------------
    ("krusevac", "Kruševac", 21.33, 43.58, "serbia", "serbian", "orthodox"),
    ("smederevo", "Smederevo", 20.95, 44.55, "serbia", "serbian", "orthodox"),
    ("rudnik", "Rudnik", 20.50, 44.13, "serbia", "serbian", "orthodox"),
    ("uzice", "Užice", 19.84, 43.86, "serbia", "serbian", "orthodox"),
    ("valjevo", "Valjevo", 19.89, 44.27, "serbia", "serbian", "orthodox"),
    ("branicevo", "Braničevo", 21.75, 44.55, "serbia", "serbian", "orthodox"),
    ("timok", "Timok", 22.28, 43.90, "serbia", "serbian", "orthodox"),
    ("novo_brdo", "Novo Brdo", 21.55, 42.55, "serbia", "serbian", "orthodox"),
    ("kosovo", "Kosovo", 20.95, 42.70, "brankovic", "serbian", "orthodox"),
    ("pec", "Peć", 20.29, 42.66, "brankovic", "serbian", "orthodox"),
    ("prizren", "Prizren", 20.74, 42.21, "brankovic", "serbian", "orthodox"),
    ("raska", "Raška", 20.00, 43.27, "brankovic", "serbian", "orthodox"),
    ("bobovac", "Bobovac", 18.18, 44.05, "bosnia", "bosnian", "bosnian_church"),
    ("usora", "Usora", 18.10, 44.75, "bosnia", "bosnian", "bosnian_church"),
    ("soli", "Soli", 18.67, 44.54, "bosnia", "bosnian", "bosnian_church"),
    ("borac", "Borač", 18.95, 43.80, "pavlovic", "bosnian", "bosnian_church"),
    ("hum", "Hum", 17.90, 43.25, "kosaca", "bosnian", "orthodox"),
    ("gacko", "Gacko", 18.53, 43.17, "kosaca", "bosnian", "orthodox"),
    ("jajce", "Jajce", 17.27, 44.34, "hrvoje", "bosnian", "catholic"),
    ("livno", "Livno", 17.00, 43.83, "hrvoje", "croatian", "catholic"),
    ("vrbas", "Vrbas", 17.19, 44.77, "hrvoje", "bosnian", "catholic"),
    ("ragusa", "Ragusa", 18.09, 42.65, "ragusa", "croatian", "catholic"),
    ("zeta", "Zeta", 19.26, 42.44, "zeta", "serbian", "orthodox"),
    ("antivari", "Antivari", 19.10, 42.09, "zeta", "serbian", "catholic"),

    # --- The Albanian lords ----------------------------------------------------------------------------------------
    ("scutari", "Scutari", 19.51, 42.07, "venice", "albanian", "catholic"),
    ("durazzo", "Durazzo", 19.52, 41.33, "venice", "albanian", "catholic"),
    ("kruja", "Krujë", 19.80, 41.50, "thopia", "albanian", "catholic"),
    ("dibra", "Dibra", 20.25, 41.65, "kastrioti", "albanian", "orthodox"),
    ("dukagjin", "Dukagjin", 19.90, 42.15, "dukagjini", "albanian", "catholic"),
    ("shpat", "Shpat", 20.08, 41.11, "arianiti", "albanian", "orthodox"),
    ("berat", "Berat", 19.95, 40.70, "muzaka", "albanian", "orthodox"),
    ("valona", "Valona", 19.49, 40.47, "valona", "albanian", "orthodox"),
    ("gjirokaster", "Gjirokastër", 20.14, 40.08, "zenebishi", "albanian", "orthodox"),

    # --- The Ottoman lands in Anatolia (İsa at Bursa, Mehmed at Amasya) --------------------------------------------
    ("bursa", "Bursa", 29.06, 40.18, "ott_isa", "turkish", "sunni"),
    ("nicaea", "Nicaea", 29.72, 40.43, "ott_isa", "turkish", "sunni"),
    ("izmit", "İzmit", 30.10, 40.75, "ott_isa", "turkish", "sunni"),
    ("karasi", "Karası", 27.88, 39.65, "ott_isa", "turkish", "sunni"),
    ("biga", "Biga", 27.24, 40.23, "ott_isa", "turkish", "sunni"),
    ("eskisehir", "Eskişehir", 30.52, 39.78, "ott_isa", "turkish", "sunni"),
    ("bolu", "Bolu", 31.60, 40.73, "ott_isa", "turkish", "sunni"),
    ("amasya", "Amasya", 35.83, 40.65, "ott_meh", "turkish", "sunni"),
    ("tokat", "Tokat", 36.55, 40.31, "ott_meh", "turkish", "sunni"),
    ("sivas", "Sivas", 37.02, 39.75, "ott_meh", "turkish", "sunni"),
    ("corum", "Çorum", 34.95, 40.55, "ott_meh", "turkish", "sunni"),
    ("ankara", "Ankara", 32.85, 39.93, "ott_meh", "turkish", "sunni"),
    ("samsun", "Samsun", 36.33, 41.29, "ott_meh", "turkish", "sunni"),

    # --- The beyliks, restored by Timur ------------------------------------------------------------------------------
    ("kastamonu", "Kastamonu", 33.78, 41.38, "candar", "turkish", "sunni"),
    ("sinop", "Sinop", 35.15, 42.02, "candar", "turkish", "sunni"),
    ("cankiri", "Çankırı", 33.62, 40.60, "candar", "turkish", "sunni"),
    ("amasra", "Amasra", 32.39, 41.75, "genoa", "greek", "orthodox"),
    ("kutahya", "Kütahya", 29.98, 39.42, "germiyan", "turkish", "sunni"),
    ("karahisar", "Karahisar", 30.54, 38.76, "germiyan", "turkish", "sunni"),
    ("usak", "Uşak", 29.40, 38.68, "germiyan", "turkish", "sunni"),
    ("manisa", "Manisa", 27.43, 38.61, "saruhan", "turkish", "sunni"),
    ("alasehir", "Alaşehir", 28.52, 38.35, "saruhan", "turkish", "sunni"),
    ("ayasoluk", "Ayasoluk", 27.35, 37.95, "aydin", "turkish", "sunni"),
    ("birgi", "Birgi", 28.00, 38.25, "aydin", "turkish", "sunni"),
    ("smyrna", "Smyrna", 27.14, 38.42, "knights", "greek", "orthodox"),
    ("milas", "Milas", 27.78, 37.31, "mentese", "turkish", "sunni"),
    ("mugla", "Muğla", 28.36, 37.21, "mentese", "turkish", "sunni"),
    ("antalya", "Antalya", 30.71, 36.90, "teke", "turkish", "sunni"),
    ("elmali", "Elmalı", 29.90, 36.70, "teke", "turkish", "sunni"),
    ("isparta", "Isparta", 30.55, 37.76, "karaman", "turkish", "sunni"),
    ("konya", "Konya", 32.49, 37.87, "karaman", "turkish", "sunni"),
    ("larende", "Larende", 33.22, 37.18, "karaman", "turkish", "sunni"),
    ("aksaray", "Aksaray", 34.03, 38.37, "karaman", "turkish", "sunni"),
    ("nigde", "Niğde", 34.68, 37.97, "karaman", "turkish", "sunni"),
    ("beysehir", "Beyşehir", 31.72, 37.68, "karaman", "turkish", "sunni"),
    ("ermenek", "Ermenek", 32.90, 36.64, "karaman", "turkish", "sunni"),
    ("silifke", "Silifke", 33.93, 36.38, "karaman", "turkish", "sunni"),
    ("alanya", "Alanya", 32.00, 36.54, "karaman", "turkish", "sunni"),
    ("kayseri", "Kayseri", 35.48, 38.73, "karaman", "turkish", "sunni"),
    ("kirsehir", "Kırşehir", 34.16, 39.15, "karaman", "turkish", "sunni"),
    ("adana", "Adana", 35.32, 37.00, "ramazan", "turkish", "sunni"),
    ("sis", "Sis", 35.82, 37.45, "ramazan", "armenian", "armenian"),
    ("elbistan", "Elbistan", 37.20, 38.20, "dulkadir", "turkish", "sunni"),
    ("maras", "Maraş", 36.93, 37.58, "dulkadir", "turkish", "sunni"),

    # --- Trebizond, the east, Georgia ----------------------------------------------------------------------------------
    ("trebizond", "Trebizond", 39.72, 41.00, "trebizond", "greek", "orthodox"),
    ("kerasous", "Kerasous", 38.39, 40.91, "trebizond", "greek", "orthodox"),
    ("lazia", "Lazia", 40.52, 41.02, "trebizond", "greek", "orthodox"),
    ("erzincan", "Erzincan", 39.50, 39.75, "timurids", "armenian", "armenian"),
    ("erzurum", "Erzurum", 41.27, 39.90, "timurids", "armenian", "armenian"),
    ("kars", "Kars", 43.10, 40.60, "timurids", "armenian", "armenian"),
    ("van", "Van", 43.38, 38.50, "timurids", "armenian", "armenian"),
    ("bitlis", "Bitlis", 42.10, 38.40, "timurids", "kurdish", "sunni"),
    ("mardin", "Mardin", 40.74, 37.31, "timurids", "kurdish", "sunni"),
    ("diyarbakir", "Diyarbakır", 40.23, 37.91, "akkoyunlu", "turkish", "sunni"),
    ("kharput", "Kharput", 39.22, 38.67, "akkoyunlu", "armenian", "armenian"),
    ("kutaisi", "Kutaisi", 42.70, 42.27, "georgia", "georgian", "orthodox"),
    ("samtskhe", "Samtskhe", 43.00, 41.65, "georgia", "georgian", "orthodox"),
    ("mingrelia", "Mingrelia", 41.90, 42.50, "georgia", "georgian", "orthodox"),
    ("abkhazia", "Abkhazia", 41.00, 43.00, "georgia", "georgian", "orthodox"),

    # --- The Mamluk Sultanate ------------------------------------------------------------------------------------------
    ("aleppo", "Aleppo", 37.16, 36.20, "mamluks", "arab", "sunni"),
    ("antioch", "Antioch", 36.16, 36.20, "mamluks", "arab", "sunni"),
    ("malatya", "Malatya", 38.31, 38.35, "mamluks", "turkish", "sunni"),
    ("ayntab", "Ayntab", 37.38, 37.06, "mamluks", "turkish", "sunni"),
    ("urfa", "Urfa", 38.79, 37.16, "mamluks", "arab", "sunni"),
    ("hama", "Hama", 36.75, 35.13, "mamluks", "arab", "sunni"),
    ("latakia", "Latakia", 35.79, 35.52, "mamluks", "arab", "sunni"),
    ("tripoli", "Tripoli", 35.84, 34.44, "mamluks", "arab", "sunni"),
    ("raqqa", "Raqqa", 39.00, 35.95, "mamluks", "arab", "sunni"),

    # --- The steppe: the Golden Horde, Crimea, the Caucasus ---------------------------------------------------------------
    ("tana", "Tana", 39.42, 47.10, "venice", "italian", "catholic"),
    ("caffa", "Caffa", 35.38, 45.03, "genoa", "italian", "catholic"),
    ("vosporo", "Vosporo", 36.47, 45.35, "genoa", "greek", "orthodox"),
    ("gothia", "Gothia", 33.90, 44.65, "theodoro", "greek", "orthodox"),
    ("solkhat", "Solkhat", 34.50, 45.30, "horde", "tatar", "sunni"),
    ("perekop", "Perekop", 33.80, 46.15, "horde", "tatar", "sunni"),
    ("yedisan", "Yedisan", 31.70, 46.90, "horde", "tatar", "sunni"),
    ("lower_dnieper", "Lower Dnieper", 33.50, 46.90, "horde", "tatar", "sunni"),
    ("kirovohrad", "Wild Fields", 32.30, 48.50, "horde", "tatar", "sunni"),
    ("poltava", "Poltava", 34.50, 49.60, "horde", "tatar", "sunni"),
    ("zaporozhia", "Zaporozhia", 35.10, 47.80, "horde", "tatar", "sunni"),
    ("donets", "Donets", 38.50, 48.50, "horde", "tatar", "sunni"),
    ("kharkiv", "Kharkiv", 36.20, 50.00, "horde", "tatar", "sunni"),
    ("mius", "Mius", 37.50, 47.10, "horde", "tatar", "sunni"),
    ("lower_don", "Lower Don", 40.60, 47.40, "horde", "tatar", "sunni"),
    ("kuban", "Kuban", 40.50, 45.50, "horde", "tatar", "sunni"),
    ("salsk", "Salsk", 42.00, 46.50, "horde", "tatar", "sunni"),
    ("stavropol", "Stavropol", 42.00, 45.05, "horde", "tatar", "sunni"),
    ("kalmyk", "Caspian Steppe", 43.80, 46.10, "horde", "tatar", "sunni"),
    ("circassia", "Circassia", 38.98, 44.60, "circassia", "circassian", "orthodox"),
    ("kabarda", "Kabarda", 43.20, 43.80, "circassia", "circassian", "orthodox"),

    # --- Italy and Sicily (the western edge) --------------------------------------------------------------------------------
    ("venice", "Venice", 12.33, 45.44, "venice", "italian", "catholic"),
    ("romagna", "Romagna", 12.20, 44.42, "papal", "italian", "catholic"),
    ("ancona", "Ancona", 13.50, 43.60, "papal", "italian", "catholic"),
    ("rome", "Rome", 12.50, 41.90, "papal", "italian", "catholic"),
    ("perugia", "Perugia", 12.39, 43.11, "papal", "italian", "catholic"),
    ("abruzzo", "Abruzzo", 13.90, 42.35, "naples", "italian", "catholic"),
    ("naples", "Naples", 14.25, 40.85, "naples", "italian", "catholic"),
    ("capitanata", "Capitanata", 15.55, 41.46, "naples", "italian", "catholic"),
    ("bari", "Bari", 16.87, 41.12, "naples", "italian", "catholic"),
    ("otranto", "Otranto", 18.17, 40.35, "naples", "italian", "catholic"),
    ("basilicata", "Basilicata", 15.80, 40.64, "naples", "italian", "catholic"),
    ("calabria", "Calabria", 16.40, 39.00, "naples", "italian", "catholic"),
    ("reggio", "Reggio", 15.80, 38.15, "naples", "italian", "catholic"),
    ("palermo", "Palermo", 13.36, 38.12, "sicily", "italian", "catholic"),
    ("catania", "Catania", 15.10, 37.50, "sicily", "italian", "catholic"),
]

# Colours of the realms on the political map (more about them in B2: rulers, dynasties, ranks).
REALM_COLORS = {
    "hungary": (196, 78, 64), "frankopan": (214, 140, 96), "wallachia": (226, 178, 52), "moldavia": (148, 64, 132),
    "ott_rum": (54, 122, 92), "ott_isa": (34, 148, 126), "ott_meh": (96, 150, 60), "byzantium": (128, 44, 120),
    "morea": (176, 92, 186), "achaea": (110, 140, 196), "athens": (70, 96, 176), "venice": (66, 156, 198),
    "genoa": (200, 60, 80), "knights": (90, 60, 50), "lesbos": (226, 120, 150), "naxos": (100, 190, 200),
    "tocco": (210, 196, 120), "ioannina": (150, 120, 200), "spata": (170, 60, 50), "zenebishi": (196, 110, 70),
    "muzaka": (130, 70, 40), "valona": (180, 150, 90), "thopia": (220, 90, 60), "kastrioti": (150, 30, 40),
    "dukagjini": (110, 40, 70), "arianiti": (230, 150, 120), "zeta": (190, 170, 220), "ragusa": (236, 220, 170),
    "serbia": (170, 50, 60), "brankovic": (200, 120, 150), "bosnia": (60, 90, 160), "hrvoje": (80, 140, 120),
    "kosaca": (140, 110, 180), "pavlovic": (120, 160, 210), "celje": (160, 200, 140), "austria": (232, 232, 232),
    "aquileia": (240, 210, 120), "salzburg": (200, 160, 200), "bavaria": (140, 180, 230), "bohemia": (210, 210, 120),
    "moravia": (230, 180, 90), "poland": (210, 70, 90), "lithuania": (190, 200, 110), "horde": (180, 140, 90),
    "theodoro": (150, 100, 140), "trebizond": (240, 170, 60), "candar": (120, 170, 180), "karaman": (100, 110, 60),
    "germiyan": (180, 200, 90), "aydin": (220, 200, 100), "saruhan": (150, 120, 60), "mentese": (90, 170, 150),
    "teke": (200, 140, 50), "dulkadir": (140, 90, 60), "ramazan": (230, 110, 90),
    "mamluks": (210, 190, 130), "akkoyunlu": (230, 230, 200), "timurids": (90, 70, 140), "georgia": (200, 60, 120),
    "circassia": (130, 150, 100), "cyprus": (240, 200, 160), "naples": (110, 120, 200), "sicily": (240, 220, 100),
    "papal": (250, 240, 220),
}

# The names written across each realm on the map.
REALM_NAMES = {
    "hungary": "Hungary", "frankopan": "Frankopan", "wallachia": "Wallachia", "moldavia": "Moldavia",
    "ott_rum": "Ottoman Rumelia", "ott_isa": "Ottomans of Bursa", "ott_meh": "Ottomans of Amasya",
    "byzantium": "Byzantium", "morea": "Morea", "achaea": "Achaea", "athens": "Athens", "venice": "Venice",
    "genoa": "Genoa", "knights": "Knights of Rhodes", "lesbos": "Lesbos", "naxos": "Naxos", "tocco": "Cephalonia",
    "ioannina": "Ioannina", "spata": "Arta", "zenebishi": "Zenebishi", "muzaka": "Muzaka", "valona": "Valona",
    "thopia": "Thopia", "kastrioti": "Kastrioti", "dukagjini": "Dukagjini", "arianiti": "Arianiti", "zeta": "Zeta",
    "ragusa": "Ragusa", "serbia": "Serbia", "brankovic": "Branković", "bosnia": "Bosnia", "hrvoje": "Hrvoje",
    "kosaca": "Kosača", "pavlovic": "Pavlović", "celje": "Celje", "austria": "Austria", "aquileia": "Aquileia",
    "salzburg": "Salzburg", "bavaria": "Bavaria", "bohemia": "Bohemia", "moravia": "Moravia", "poland": "Poland",
    "lithuania": "Lithuania", "horde": "Golden Horde", "theodoro": "Theodoro", "trebizond": "Trebizond",
    "candar": "Candar", "karaman": "Karaman", "germiyan": "Germiyan", "aydin": "Aydın", "saruhan": "Saruhan",
    "mentese": "Menteşe", "teke": "Teke", "dulkadir": "Dulkadir", "ramazan": "Ramazan",
    "mamluks": "Mamluk Sultanate", "akkoyunlu": "Ak Koyunlu", "timurids": "Timurids", "georgia": "Georgia",
    "circassia": "Circassia", "cyprus": "Cyprus", "naples": "Naples", "sicily": "Sicily", "papal": "Papal States",
}

# --- the land's riches ------------------------------------------------------------------------------
# The main good each province produces (others follow from its terrain: tools/provinces.py).
GOODS = {
    # metals and salt: the Balkan and Carpathian mines
    "novo_brdo": "silver", "rudnik": "silver", "borac": "silver", "zolyom": "gold", "szatmar": "gold",
    "gyulafehervar": "gold", "hradec": "silver", "kosovo": "silver", "bobovac": "iron", "graz": "iron",
    "carinthia": "iron", "sofia": "iron", "kutaisi": "iron", "trencsen": "copper", "szepes": "copper",
    "kolozsvar": "salt", "szekelyfold": "salt", "maramaros": "salt", "krakow": "salt", "soli": "salt",
    "arges": "salt", "roman": "salt", "ragusa": "salt", "salzburg": "salt", "manisa": "alum", "kutahya": "alum",
    # wine, oil, sugar, mastic, silk, cotton
    "kassa": "wine", "eger": "wine", "monemvasia": "wine", "candia": "wine", "canea": "olive_oil",
    "limassol": "sugar", "chios": "mastic", "lesbos": "olive_oil", "athens": "olive_oil", "naxos": "wine",
    "bursa": "silk", "trebizond": "silk", "ayasoluk": "cotton", "milas": "cotton", "adana": "cotton",
    "nicosia": "cotton", "corfu": "olive_oil", "zakynthos": "wine", "patras": "wine", "kalamata": "olive_oil",
    "thebes": "silk", "brasso": "cloth", "szeben": "cloth", "prague": "cloth", "vienna": "wine", "venice": "glass",
    "aleppo": "spices", "constantinople": "cloth", "caffa": "grain", "tana": "furs", "edirne": "cloth",
    # the forests and the steppe
    "kyiv": "furs", "chernihiv": "furs", "lutsk": "wax", "zhytomyr": "wax", "suceava": "wax", "hotin": "wax",
    "soroca": "livestock", "orhei": "wax", "lapusna": "livestock", "iasi": "livestock", "barlad": "livestock",
    "targoviste": "wax", "buzau": "livestock", "ialomita": "livestock", "braila": "fish", "chilia": "fish",
    "cetatea_alba": "fish", "vosporo": "fish", "lower_don": "fish", "khadjibey": "grain", "dobruja": "grain",
    "rodosto": "grain", "larissa": "grain", "vlasia": "timber", "teleorman": "grain", "caracal": "grain",
    "solkhat": "horses", "perekop": "horses", "yedisan": "horses", "lower_dnieper": "horses", "zaporozhia": "horses",
    "donets": "horses", "kharkiv": "horses", "poltava": "horses", "kirovohrad": "horses", "mius": "horses",
    "kuban": "horses", "salsk": "horses", "stavropol": "horses", "kalmyk": "horses", "elbistan": "horses",
    "palermo": "grain", "catania": "sugar", "bari": "olive_oil", "otranto": "olive_oil", "capitanata": "grain",
}

# People, in thousands, living in the province's great town (added to the countryside around it).
CITIES = {
    "venice": 110, "constantinople": 50, "naples": 40, "prague": 35, "aleppo": 50, "rome": 25, "bursa": 30,
    "edirne": 25, "thessaloniki": 25, "caffa": 20, "palermo": 30, "vienna": 20, "buda": 12, "krakow": 15,
    "breslau": 18, "candia": 15, "nicosia": 15, "trebizond": 12, "konya": 12, "sinop": 8, "ragusa": 6,
    "brasso": 8, "szeben": 7, "kassa": 7, "pozsony": 6, "zagreb": 5, "lwow": 6, "kyiv": 8, "suceava": 6,
    "targoviste": 6, "sofia": 8, "tarnovo": 6, "skopje": 8, "athens": 6, "thebes": 5, "mystras": 6, "rhodes": 8,
    "famagusta": 8, "chios": 6, "ayasoluk": 6, "antioch": 8, "hama": 15, "tripoli": 15, "erzurum": 10,
    "kutaisi": 6, "cetatea_alba": 8, "chilia": 6, "novo_brdo": 8, "zara": 6, "spalato": 5, "durazzo": 4,
    "ankara": 10, "amasya": 8, "tokat": 8, "sivas": 10, "kayseri": 10, "antalya": 6, "manisa": 6,
}

# Fortifications in 1402: 0 none, 1 a castle, 2 strong walls, 3 a great fortress, 4 Constantinople's walls.
FORTS = {
    "constantinople": 4, "rhodes": 3, "monemvasia": 3, "corinth": 3, "belgrade": 3, "ragusa": 3, "venice": 3,
    "thessaloniki": 2, "edirne": 2, "bursa": 2, "buda": 2, "suceava": 2, "cetatea_alba": 2, "chilia": 2,
    "giurgiu": 2, "vidin": 2, "nikopol": 2, "kruja": 2, "scutari": 2, "durazzo": 2, "mystras": 2, "nauplia": 2,
    "modon": 2, "candia": 2, "caffa": 2, "trebizond": 2, "krakow": 2, "prague": 2, "vienna": 2, "hunyad": 2,
    "szeben": 2, "brasso": 2, "branicevo": 2, "smederevo": 1, "targoviste": 2, "arges": 2, "tarnovo": 2,
    "novo_brdo": 2, "bobovac": 2, "jajce": 2, "zeta": 1, "ioannina": 2, "arta": 2, "athens": 2, "thebes": 1,
    "famagusta": 2, "nicosia": 2, "chios": 2, "lesbos": 2, "kos": 2, "smyrna": 2, "sinop": 2, "kastamonu": 2,
    "konya": 2, "amasya": 2, "tokat": 1, "aleppo": 2, "antioch": 2, "erzurum": 2, "kutaisi": 1, "gothia": 2,
    "naples": 2, "rome": 1, "palermo": 2, "zara": 2, "spalato": 1, "kotor": 2, "severin": 2, "karansebes": 1,
    "temes": 2, "varad": 1, "kolozsvar": 1, "gyulafehervar": 2, "pozsony": 2, "esztergom": 2, "zagreb": 1,
    "lwow": 2, "kamieniec": 2, "lutsk": 2, "kyiv": 1, "salona": 1, "zitouni": 1, "larissa": 1,
}

# Low, wet ground: the Danube's delta and floodplain, the Kuban's mouths.
MARSHES = {"chilia", "braila", "kuban"}
